services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/SJobs
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Poiki043!
      - POSTGRES_DB=SJobs
      - POSTGRES_HOST=10.180.190.181
      - POSTGRES_PORT=5432
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
